# Global: every profile, every machine.

# --- Runtime managers ---
brew "mise"

# --- Shell & core CLI ---
brew "chezmoi"
brew "direnv"
brew "fzf"
brew "jq"
brew "mas"
brew "pure"
brew "zsh-syntax-highlighting"

# --- CLI tools ---
brew "bat"
brew "diff-so-fancy"
brew "entr"
brew "eza"
brew "ffmpeg"
brew "fzf-tab"
brew "gh"
brew "gifsicle"
brew "git-lfs"
brew "gnupg"
brew "imagemagick"
brew "mkcert"
brew "mole"
brew "pandoc"
brew "poppler"
brew "ruff"
brew "shellcheck"
brew "shfmt"
brew "tesseract"
brew "wget"
brew "worktrunk"

# Global
cask "1password-cli"
cask "antigravity"
cask "chatgpt"
cask "claude"
cask "docker-desktop"
cask "flux-app"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "hazel"
cask "karabiner-elements"
cask "keycastr"
cask "libreoffice"
cask "mos"
cask "mutedeck"
cask "notunes"
cask "obsidian"
cask "ollama-app"
cask "sf-symbols"
cask "shottr"
cask "slack"
cask "superhuman"
cask "textbuddy"
cask "the-unarchiver"
cask "visual-studio-code"
cask "zed"
cask "vivaldi"
cask "zoom"

# fonts
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-monoid"
