#!/usr/bin/env ruby
require 'shellwords'

HELP_TEXT = <<~HELP
  Usage: ocrify FILE

  Perform OCR (Optical Character Recognition) on an image or PDF file.

  ARGUMENTS:
    FILE   Path to image or PDF file to perform OCR on

  OPTIONS:
    -h, --help  Show this help message

  DESCRIPTION:
    Converts the input file to TIFF format using ImageMagick, then uses
    Tesseract to perform OCR and generate a searchable PDF.
    Output file will be named FILENAME-ocred.pdf
HELP

def ocrify_file(filename)
  filename_parts = filename.split('.')
  file_extension = filename_parts.last
  filename_no_extension = filename_parts.take(filename_parts.size - 1).join('.')

  convert_cmd = "convert -density 300 #{Shellwords.escape(filename)} -type Grayscale -compress lzw -background white -flatten +matte -depth 32 #{Shellwords.escape(filename_no_extension)}.tif"
  tesseract_cmd = "tesseract #{Shellwords.escape(filename_no_extension)}.tif #{Shellwords.escape(filename_no_extension)}-ocred -l eng pdf"

  puts "Converting to TIFF..."
  system(convert_cmd)

  puts "Running OCR..."
  system(tesseract_cmd)
end



f = ARGV.first

if f.nil? || ['-h', '--help'].include?(f)
  puts HELP_TEXT
  exit 0
end

ocrify_file(f)
