[tools]
node = "24"
python = "3.14"
go = "1.26"
pnpm = "10"
uv = "latest"

# Global tools - node
#  Codex & Gemini would typically use homebrew; they ship new releases all the time.
#  Brew releases lag too much, so we use node instead
"npm:@openai/codex" = "latest" 
"npm:@google/gemini-cli" = "latest"

# Global tools - python
# These would normally use homebrew, but they all pull in a brew python.  So, mise it is
"pipx:yamllint" = "latest"
"pipx:ocrmypdf" = "latest"
"pipx:mdformat" = { version = "latest", uvx_args = "--with mdformat-gfm --with mdformat-frontmatter" }

[settings.python]
uv_venv_auto = "create|source"
github_attestations = false

[settings.pipx]
uvx = true

[settings.npm]
package_manager = "pnpm"


